"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import {
  PenIcon,
  SparklesIcon,
  CopyIcon,
} from "@/components/icons"

const contentTypes = [
  { id: "essay", label: "Essay" },
  { id: "article", label: "Article" },
  { id: "report", label: "Report" },
  { id: "assignment", label: "Assignment" },
  { id: "research", label: "Research Outline" },
]

const lengths = [
  { id: "short", label: "Short (300 words)" },
  { id: "medium", label: "Medium (600 words)" },
  { id: "long", label: "Long (1000+ words)" },
]

interface AIWriterProps {
  onBack: () => void
}

export function AIWriter({ onBack }: AIWriterProps) {
  const [topic, setTopic] = useState("")
  const [contentType, setContentType] = useState("essay")
  const [length, setLength] = useState("medium")
  const [generatedContent, setGeneratedContent] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGenerate = () => {
    if (!topic.trim()) return

    setIsGenerating(true)

    setTimeout(() => {
      const sampleContent = `# ${topic}

## Introduction

${topic} is a fascinating subject that has garnered significant attention in recent years. This ${contentType} explores the key aspects, implications, and future directions of this important topic.

Understanding ${topic} requires a comprehensive examination of its fundamental principles and real-world applications. In the following sections, we will delve into the core concepts, analyze relevant research, and discuss practical implications.

## Background and Context

The study of ${topic} has evolved considerably over time. Initially, researchers focused on basic observations and theoretical frameworks. However, modern approaches incorporate advanced methodologies and interdisciplinary perspectives.

Key developments in this field include:
- **Foundational theories** that established the groundwork for current understanding
- **Technological advances** that enabled new forms of research and analysis
- **Cross-disciplinary collaboration** that brought fresh insights and methodologies

## Main Discussion

The central aspects of ${topic} can be examined through multiple lenses. First, we consider the theoretical framework that underpins our understanding. This involves examining the core principles and their logical foundations.

Second, practical applications demonstrate how these theories translate into real-world impact. From everyday scenarios to specialized contexts, the relevance of ${topic} becomes increasingly apparent.

Third, emerging trends suggest exciting possibilities for future development. Innovations in technology and methodology continue to expand what we know and can achieve.

## Analysis and Findings

Research on ${topic} has yielded several important insights:

1. **Primary finding**: The fundamental principles remain robust across various contexts
2. **Secondary finding**: Practical applications continue to evolve and expand
3. **Tertiary finding**: Future prospects appear promising with continued research

These findings have significant implications for both theory and practice. They suggest that continued investment in understanding ${topic} will yield valuable returns.

## Conclusion

In conclusion, ${topic} represents a vital area of study with substantial implications for our understanding and practical applications. The evidence presented demonstrates the importance of continued research and development in this field.

As we look to the future, the potential for new discoveries and innovations remains high. By maintaining rigorous standards of inquiry and embracing interdisciplinary collaboration, we can continue to advance our knowledge and capabilities.

---

*This content was generated by AI Study Super App*`

      setGeneratedContent(sampleContent)
      setIsGenerating(false)
    }, 2000)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent)
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/20">
          <PenIcon className="h-5 w-5 text-accent" />
        </div>
        <div className="flex-1">
          <h2 className="font-semibold text-foreground">AI Writer</h2>
          <p className="text-sm text-muted-foreground">Generate essays, articles, and more</p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={onBack}
          className="border-border text-foreground hover:bg-secondary"
        >
          Back
        </Button>
      </div>

      {/* Topic Input */}
      <div>
        <label className="mb-2 block text-sm font-medium text-foreground">Topic</label>
        <textarea
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          placeholder="Enter your topic or title..."
          className="h-24 w-full resize-none rounded-xl border border-border bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
        />
      </div>

      {/* Content Type */}
      <div>
        <label className="mb-2 block text-sm font-medium text-foreground">Content Type</label>
        <div className="flex flex-wrap gap-2">
          {contentTypes.map((type) => (
            <button
              key={type.id}
              onClick={() => setContentType(type.id)}
              className={cn(
                "rounded-full px-4 py-2 text-sm font-medium transition-colors",
                contentType === type.id
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
              )}
            >
              {type.label}
            </button>
          ))}
        </div>
      </div>

      {/* Length */}
      <div>
        <label className="mb-2 block text-sm font-medium text-foreground">Length</label>
        <div className="flex flex-wrap gap-2">
          {lengths.map((l) => (
            <button
              key={l.id}
              onClick={() => setLength(l.id)}
              className={cn(
                "rounded-full px-4 py-2 text-sm font-medium transition-colors",
                length === l.id
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
              )}
            >
              {l.label}
            </button>
          ))}
        </div>
      </div>

      {/* Generate Button */}
      <Button
        onClick={handleGenerate}
        disabled={!topic.trim() || isGenerating}
        className="w-full gap-2 bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
      >
        {isGenerating ? (
          <>
            <div className="h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground border-t-transparent" />
            Generating...
          </>
        ) : (
          <>
            <SparklesIcon className="h-4 w-4" />
            Generate Content
          </>
        )}
      </Button>

      {/* Generated Content */}
      {generatedContent && (
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="mb-3 flex items-center justify-between">
            <h3 className="font-medium text-foreground">Generated Content</h3>
            <Button
              variant="outline"
              size="sm"
              onClick={copyToClipboard}
              className="gap-2 border-border text-foreground hover:bg-secondary"
            >
              <CopyIcon className="h-4 w-4" />
              Copy
            </Button>
          </div>
          <div className="prose prose-invert max-h-96 max-w-none overflow-y-auto text-sm text-muted-foreground">
            <pre className="whitespace-pre-wrap font-sans">{generatedContent}</pre>
          </div>
        </div>
      )}
    </div>
  )
}
